### Get all contacts
GET http://localhost:3000/contacts

### Get one contact by ID
GET http://localhost:3000/contacts/696aba0206d496077bfdfc21
### Get one contact by ID
GET http://localhost:3000/contacts/696aba0206d496077bfdfc22
### Get one contact by ID
GET http://localhost:3000/contacts/696aba0206d496077bfdfc23



### POST
POST http://localhost:3000/contacts
Content-Type: application/json

{
  "firstName": "Adam",
  "lastName": "Nielsen",
  "email": "adam@test.com",
  "favoriteColor": "Blue",
  "birthday": "1990-01-01"
}

### PUT
PUT http://localhost:3000/contacts/69751c48d833433feaccf82c
Content-Type: application/json

{
  "firstName": "Adam",
  "lastName": "Nielsen",
  "email": "updated@test.com",
  "favoriteColor": "Green",
  "birthday": "1990-01-01"
}

### DELETE
DELETE http://localhost:3000/contacts/69751c48d833433feaccf82c


### Create Contact (POST)
POST https://cse341-kqba.onrender.com/contacts
Content-Type: application/json

{
  "firstName": "Adam",
  "lastName": "Tester",
  "email": "adam@test.com",
  "favoriteColor": "Blue",
  "birthday": "1995-01-15"
}

### Update Contact (PUT)
PUT https://cse341-kqba.onrender.com/contacts/697522439401bdd29113e6e4
Content-Type: application/json

{
  "firstName": "Adam",
  "lastName": "Updated",
  "email": "adam.updated@test.com",
  "favoriteColor": "Green",
  "birthday": "1995-01-15"
}

### Delete Contact (DELETE)
DELETE https://cse341-kqba.onrender.com/contacts/697522439401bdd29113e6e4
